---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.14
  labels:
    derrick.service: lucas
  name: lucas
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    derrick.service: lucas
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.14
  labels:
    derrick.service: lucas
  name: lucas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: lucas
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2
        name: web
        ports:
        - containerPort: 8080
        env:
        - name: CA_FILE
          value: /etc/kubernetes/pki/etcd/ca.pem
        - name: CERT_FILE
          value: /etc/kubernetes/pki/etcd/etcd-client.pem
        - name: KEY_FILE
          value: /etc/kubernetes/pki/etcd/etcd-client-key.pem
        - name: ENDPOINTS
          value: "{{ENDPOINTS}}"
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs-0
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki/etcd
          type: DirectoryOrCreate
        name: etcd-certs-0
